Added the eucan-connect code
molgenis/molgenis-py-eucan-connect pull request #2
Opened 2021-11-24 10:34 UTC by dtroelofsprins

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] Updated CHANGELOG.md

2021-11-30 16:01 UTC, tommydeboer requested changes

2021-12-07 10:56 UTC, tommydeboer requested changes

2021-12-07 10:56 UTC, tommydeboer commented on src/molgenis/eucan_connect/mica.py
> +            "query=study(limit(" + str(start) + "," + str(batch_size) + "),fields(*))"
You can use string formatting here, which reads a bit nicer:

```suggestion
            f"query=study(limit({str(start)},{str(batch_size)}"),fields(*))"
```

2021-12-09 10:24 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/errors.py
> +    shouldn't cancel the current action (for example staging or publishing).
Changed

2021-12-09 10:24 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/errors.py
> +    Summary object. Stores errors and warnings that occurred for each node.
Changed

2021-12-09 10:57 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan.py
> +            catalogue_data = self._get_mica_data(catalogue)
Your right!

2021-12-09 11:34 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan.py
> +            print("Birth cohort data. No module available yet!")
It actually could be removed at all, although this catalogue type is available in the database. I left it there and in stead of a print or warning raise an EucanError.

2021-12-09 11:35 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan.py
> +                self.session, IsoCountryData, self.ref_data, self.printer
Changed this, a bit strange how this ended up in the final version.

2021-12-09 11:50 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan.py
> +        self.warnings = []
True

2021-12-09 11:50 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan.py
> +        self.warnings = []
True

2022-02-02 07:19 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/importer.py
> +    def import_data(self, data: dict, data_cat: str) -> List[EucanWarning]:
You are right. I've changed this and created indeed two separate functions.

2022-02-02 08:12 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan.py
> +        report.add_warnings(ref_data.ref_entity, warnings)
I thought it was the correct value, but you are right, this should be the catalogue. I've changed this.

2022-02-02 08:39 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/model.py
> +#     studies: List[dict]
Done

2022-02-02 08:39 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/printer.py
> +# from molgenis.eucan_connect.errors import EucanError #, EucanWarning, EucanReport
Done

2022-02-02 08:39 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/printer.py
> +    #         self.print(message)
Yes, this was a todo, now done.

2022-02-02 08:44 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan_client.py
> +        self.warnings: List[EucanWarning] = []
True, removed them.

2022-02-02 08:45 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/importer.py
> +                raise EucanError(f"Error importing rows to {entity_type_id}") from e
True, but then the data must be modelled in the right way like NodeData/CatalogueData/RefData

2022-02-02 08:46 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan_client.py
> +        return ref_data
Changed the return type to List[dict]

2022-02-02 08:50 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/importer.py
> +        self.printer.indent()
Changed.

2022-02-02 08:51 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/mica.py
> +            "query=study(limit(" + str(start) + "," + str(batch_size) + "),fields(*))"
Implemented

2022-02-02 10:54 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan_client.py
> +        return RefData.from_dict(ref_entity=RefEntity, tables=tables)
Removed the refentity=RefEntity, as it turnes out that it has no function. Tested the code (both technical as well as functional) and without this all works OK.

2022-02-23 13:22 UTC, tommydeboer requested changes

2022-02-23 13:22 UTC, tommydeboer commented on src/molgenis/eucan_connect/model.py
> +                ),
Didn't know about this one, nice! :) I think this notation is a bit easier to read though:

```python
iso_country = next(
    filter(lambda country: country[iso_type] == country_description, self.iso_country_data),
    False)
```

2022-02-23 13:22 UTC, tommydeboer commented on src/molgenis/eucan_connect/model.py
> +    #  @property TODO: is dit een property?
Resolve this TODO

2022-02-23 13:22 UTC, tommydeboer commented on src/molgenis/eucan_connect/model.py
> +            # ref_entity=ref_entity,
🧼 🧽

2022-02-23 13:22 UTC, tommydeboer commented on src/molgenis/eucan_connect/model.py
> +    # ref_entity: RefEntity
🧼 🧽

2022-02-23 13:22 UTC, tommydeboer commented on tests/conftest.py
> +    # eucan.iso_country_data: country_data
🧼

2022-02-23 13:22 UTC, tommydeboer commented on tests/test_eucan.py
> +    # ]
Same here

2022-02-23 13:22 UTC, tommydeboer commented on tests/test_importer.py
> +    # assert importer._get_eucan_ids.assert_called_once()
Same here

2022-02-23 13:22 UTC, tommydeboer commented on tests/test_lifecycle.py
> +        # np.testing.assert_array_equal(converted_ndarrays, check_ndarrays)
🧼 or enable

2022-03-02 10:25 UTC, dtroelofsprins commented on README.md
> +These tools can be used as a library in a script or as a command line tool. In both
True, I've removed it.

2022-03-02 10:27 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/mica.py
> +                )
That's useful to know, this piece of code is rewritten and not used anymore, but I'll check if I've used something like this in another place.

2022-03-02 10:42 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/mica.py
> +    def get_mica_study_data(self, mica_studies: List):
I didn't know what to use when it was used a "normal" list (for dict's I knew), thanks!

2022-03-02 10:47 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan.py
> +    def _create_catalogue_data(
True and done

2022-03-02 10:47 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/eucan.py
> +    def get_uploadable_data(
I agree, included it into the EucanSession

2022-03-04 07:17 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/importer.py
> +                    f"No new data needs to be imported " f"in {entity_type_id}"
🤔, that's really strange, I think reformatting when committing has done this. I've changed it.

2022-03-04 07:56 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/lifecycle.py
> +                #    "events_type_administrative_databases",
I've checked it again, and decided areasOfInformation can indeed be mapped to type of administrative databases.

2022-03-04 07:58 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/lifecycle.py
> +        # TODO Discuss: As not all persons have a contribution type,
Done

2022-03-04 10:09 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/lifecycle.py
> +        # TODO: ik krijg dit (nog) niet in een stap.
After a bit of trial and error, I've managed to create a function that does it in one step.

2022-03-04 10:12 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/model.py
> +            # ref_entity=ref_entity,
Done

2022-03-04 10:12 UTC, dtroelofsprins commented on src/molgenis/eucan_connect/model.py
> +    # ref_entity: RefEntity
Done

2022-03-04 10:13 UTC, dtroelofsprins commented on tests/conftest.py
> +    # eucan.iso_country_data: country_data
Done

2022-03-04 10:29 UTC, dtroelofsprins commented on tests/test_eucan.py
> +    # ]
= Solved

2022-03-09 11:26 UTC, dtroelofsprins commented on tests/test_eucan.py
> +    #                                            "study")
No, finally I found a way that the function within the function still works, but you can also mock it:
You can set the side effect of the mock to be the original method.

2022-03-10 11:00 UTC, dtroelofsprins commented on tests/test_importer.py
> +    # assert importer._get_eucan_ids.assert_called_once()
Solved

2022-03-10 11:00 UTC, dtroelofsprins commented on tests/test_lifecycle.py
> +    #  _group_column_information?
Done

2022-03-10 11:27 UTC, dtroelofsprins commented on tests/test_lifecycle.py
> +        # np.testing.assert_array_equal(converted_ndarrays, check_ndarrays)
Done

2022-03-24 12:54 UTC, tommydeboer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[#8715] Finish EUCAN-Connect PR](https://trello.com/c/Ecze7FKy/427-8715-finish-eucan-connect-pr)

2022-03-29 06:54 UTC, tommydeboer approved these changes

2022-03-29 06:54 UTC, merged